sudo: required
language: generic 
services:
 - docker

before_install:
  - docker build -t weinghwee/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true weinghwee/react-test npm test

after_success:
  - docker build -t weinghwee/multi-client ./client
  - docker build -t weinghwee/multi-nginx ./nginx
  - docker build -t weinghwee/multi-server ./server
  - docker build -t weinghwee/multi-worker ./worker